# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- script: |
    git clone https://meganii$(GITHUB_PARSONAL_ACCESS_TOKEN)@github.com/meganii/test-deploy-to-gh-pages-from-azure-piplines.git
    cd test-deploy-to-gh-pages-from-azure-piplines
    git config --local user.name $(GIT_USER)
    git config --local user.email $(GIT_EMAIL)
    echo "hello from Azure" > index.html
    git add --all
    git commit -m "[skip ci] build from azure"
    git push -f origin master
    displayName: 'Deploy to GitHub Pages'