DefaultContentLanguage: "ja"

title: "SIS Lab"
baseURL: "https://meganii.com/"
permalinks:
  blog: "/blog/:year/:month/:day/:slug/"

Languages:
  ja:
    lang: ""
    title: "SIS Lab"
    description: "元じょーぶん生によるメーカー系SIerブログ。趣味のプログラミング、旅行。日々、学んだことについて書きます。"
  en:
    lang: "en/"
    title: "SIS Lab"
    description: "English desc"
    weight: 2
    params:
      linkedin: "english-link"
    permalinks:
      blog: "/blog/en/:year/:month/:day/:slug/"

contentDir: "content"
publishDir: "public"

rssuri: "feed.xml"

Params:
  Author: "meganii"
  Birth: "Sun, March 3, 1988"
  DateForm: "Mon, Jan 2, 2006"
  GoogleAnalyticsUserID: "UA-55005303-5"
  Twitter: "meganii"
  Github: "https://github.com/meganii"
  ShowTagCloud: True
  ShowRelatedPost: True
  Disqus: "meganii"
  SyntaxHighlightTheme: "solarized_dark.min.css"
  logo: "/images/meganii_logo.png"

MetadataFormat: "yaml"

taxonomies:
  tag: "tags"
  category: "category"

author:
    name: "meganii"
    homepage: "https://meganii.com/"

Copyright:
