name: Create PR for AMP

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install

      - name: Set current datetime as env variable
        env:
          TZ: 'Asia/Tokyo'
        run: echo "CURRENT_DATETIME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Create new branch
        run: |
          git switch -c bump_amp_${{ env.CURRENT_DATETIME }}
          git push -u origin bump_amp_${{ env.CURRENT_DATETIME }}

      - name: Run Script
        run: sh script/confirmAndUpdateAMPVersion.sh

      - name: Add and commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -N .
          git diff --name-only --exit-code
        continue-on-error: true
    
      - name: Commit files
        run: |
          git add --all
          git commit -m "Bump amp version"
          git push 

      - name: create pull request
        run: gh pr create --head bump_amp_${{ env.CURRENT_DATETIME }} --title "Bump amp version" --body ""
        env:
          GH_TOKEN: ${{ github.token }}