name: Update Hugo Modules

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.146.5'

      - name: Update Hugo Modules
        run: |
          hugo mod get -u
          hugo mod tidy

      - name: Commit & Push updates
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add go.mod go.sum
          git commit -m "Update Hugo modules from content-vault $(date)"
          git push origin main